#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Setup default values
host = data.get("host")
h2hs = data.get("http2https", True)

agent.set_env("TRAEFIK_HOST", host)
agent.set_env("TRAEFIK_HTTP2HTTPS", h2hs)

agent.set_env("BASE_DOMAIN",data.get("base_domain",""))
agent.set_env("DNS_OVERRIDE",data.get("dns_override",""))
agent.set_env("DNS_LIST",data.get("dns_list"))
agent.set_env("SPLIT_DNS_LIST",data.get("split_dns_list"))
agent.set_env("ISSUER",data.get("issuer",""))
agent.set_env("CLIENT_ID",data.get("client_id",""))
agent.set_env("CLIENT_SECRET",data.get("client_secret",""))
agent.set_env("PKCE",data.get("pkce",""))
