#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

agent.set_env("ISSUER",data.get("issuer",""))
agent.set_env("CLIENT_ID",data.get("client_id",""))
agent.set_env("CLIENT_SECRET",data.get("client_secret",""))
