#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import agent
import agent.tasks

# Find default traefik instance for current node
default_traefik_id = agent.resolve_agent_id('traefik@node')
if default_traefik_id is None:
    sys.exit(2)

headscale_ui_tcp_port = os.getenv('HEADSCALE_UI_TCP_PORT')

if headscale_ui_tcp_port:
    agent.set_env("HEADPLANE_TCP_PORT", headscale_ui_tcp_port)
    # Configure headplane route
    set_route_data = {
        'instance': os.environ['MODULE_ID']+'-headplane',
        'url':  'http://127.0.0.1:' + headscale_ui_tcp_port,
        'host': os.environ["TRAEFIK_HOST"],
        'path': '/admin',
        'http2https': os.environ["TRAEFIK_HTTP2HTTPS"]==True,
        'lets_encrypt_check': True,
        'lets_encrypt_cleanup': True,
    }
    set_route_data['lets_encrypt'] = agent.get_route(os.environ['MODULE_ID']).get('lets_encrypt', False)
    agent.set_route(set_route_data)
    agent.unset_env("HEADSCALE_UI_TCP_PORT")
