#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}

# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST","")
config["base_domain"] = os.getenv("BASE_DOMAIN","")
config["dns_override"] = os.getenv("DNS_OVERRIDE") == "True"
config["dns_list"] = os.getenv("DNS_LIST","")
config["split_dns_list"] = os.getenv("SPLIT_DNS_LIST","")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"
config["issuer"] = os.getenv("ISSUER","")
config["client_id"] = os.getenv("CLIENT_ID","")
config["client_secret"] = os.getenv("CLIENT_SECRET","")
config["pkce"] = os.getenv("PKCE") == "True"

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
